### ISSUE TITLE
Are you planning to incorporate the MitoAnnotator into this pipeline?

### ISSUE THREAD

**Issue by gleisonm** [billzt/MiFish#10]
Hi, I really like your tool, however, I have many samples to analyze and I am encountering difficulties using your tool via the web service. I would like to know if you plan to implement this tool for the Linux terminal.

**Comment by tao-bioinfo** [comment]
Hi @gleisonm 

Although we don't plan to release a standalone version of MitoAnnotator now (largely due to time limits since we are convincing ourselves to another project), the web service can accept a FASTA file including multiple sequences, and they can be analyzed in parallel. I recommend that a FASTA file including five to ten sequences is favorable.

**Comment by gleisonm** [comment]
Hi, @billzt.
 May I inquire if you have a script available that could be shared to facilitate the execution via the terminal? I have numerous reads, and utilizing the web service is proving to be impractical. I'd like to highlight that even with the default parameters, your tool is the only one that annotates and shift the position genes exactly as I need.

**Comment by tao-bioinfo** [comment]
May I ask that how many "reads" do you have? MitoAnnotator is used to annotate complete or near complete mitogenomes, which means that the length of your sequences should be near to ~16kb.

**Comment by gleisonm** [comment]
About 50 complete mitochondrial DNA genomes, and there might be more coming.

**Comment by gleisonm** [comment]
I have been attempting to integrate your tool with others in a Nextflow pipeline for the purpose of uploading the results to NCBI's database.

**Comment by tao-bioinfo** [comment]
Got it. Perhaps we will plan to release a standalone version after finishing the in-hand project.

Besides, now we have added a new option called "Visualization" in the web service. Turn it off will skip the Visualization step and get an additional 50% speed up.
