### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by zhangjl-work** [billzt/MiFish#14]
Sample WFPPS13 Step 0: Decompress
Sample WFPPS13 Step 1: filter the quality of FASTQ and merge Pair-End Reads
Sample WFPPS13 Step 2: filter read length and remove primers
Sample WFPPS13 Step 3: De-noise and generate haploid
Traceback (most recent call last):
  File "/usr/local/bin/mifish", line 33, in <module>
    sys.exit(load_entry_point('mifish', 'console_scripts', 'mifish')())
  File "/MiFish/mifish/cmd/mifish.py", line 76, in main
    pipeline.runMiFish(data_dir=args.seq_dir, data_dir_other_groups=data_dir_other_groups, \
  File "/MiFish/mifish/core/pipeline.py", line 215, in runMiFish
    sizeFasIntegrator.run(zotusCountFile=f'{workdir_sample}/03_haploid/{sample_name}.zotus.size.txt', \
  File "/MiFish/mifish/core/sizeFasIntegrator.py", line 9, in run
    (zotu, count) = line.strip().split()
ValueError: too many values to unpack (expected 2)

colorsp When I skip this sample, the program runs normally.  My data doesn't seem to have any problems.

**Comment by tao-bioinfo** [comment]
`File "/MiFish/mifish/core/sizeFasIntegrator.py", line 9, in run`

It seems you are running version 1.x. How about upgrading to the latest version?

**Comment by zhangjl-work** [comment]
> `File "/MiFish/mifish/core/sizeFasIntegrator.py", line 9, in run`
> 
> It seems you are running version 1.x. How about upgrading to the latest version?

installed it this way, how do I update it? 
docker pull taobioinfo/mifish:latest

**Comment by tao-bioinfo** [comment]
`taobioinfo/mifish:latest` has pointed to v2.0 since five weeks ago. I think you can run `docker pull taobioinfo/mifish:latest` again. And you can see the version via `docker image ls`

**Comment by zhangjl-work** [comment]
> `taobioinfo/mifish:latest` has pointed to v2.0 since five weeks ago. I think you can run `docker pull taobioinfo/mifish:latest` again. And you can see the version via `docker image ls`

Problem solved. Thank you very much
