### ISSUE TITLE
Issue with crabs db_download with mitofish

### ISSUE THREAD

**Issue by wxy23116** [billzt/MiFish#5]
I am trying to download the mitofish database using the crabs conda installation (as far as I know Docker does not play well on the NeSI infrastructure). We are getting the following error:
      crabs db_download --source mitofish --output mitofish.fasta --keep_original yes

downloading sequences from the MitoFish database
Traceback (most recent call last):
  File "/nesi/nobackup/uoo03004/alana_crabs/crabs/crabs_env/bin/crabs", line 1372, in <module>
    main()
  File "/nesi/nobackup/uoo03004/alana_crabs/crabs/crabs_env/bin/crabs", line 1369, in main
    args.func(args)
  File "/nesi/nobackup/uoo03004/alana_crabs/crabs/crabs_env/bin/crabs", line 96, in db_download
    dl_file = mitofish_download(url)
  File "/nesi/nobackup/uoo03004/alana_crabs/crabs/crabs_env/lib/python3.6/site-packages/function/module_db_download.py", line 139, in mitofish_download
    os.remove('complete_partial_mitogenomes.zip')
FileNotFoundError: [Errno 2] No such file or directory: 'complete_partial_mitogenomes.zip'

**Comment by tao-bioinfo** [comment]
Sorry for my late reply, but which version of crabs do you use? The conda version seems to be v0.1.1, too old to execute. Please try install from the GitHub, which includes many fixes

**Comment by wxy23116** [comment]
Thanks for the reply, I will try again.


| |
wangxiaoyang22919
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 8/8/2023 18:50 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [billzt/MiFish] Issue with crabs db_download with mitofish (Issue #5) |

Sorry for my late reply, but which version of crabs do you use? The conda version seems to be v0.1.1, too old to execute. Please try install from the GitHub, which includes many fixes

**Comment by cement-head** [comment]
The GitHub version works without issues.

**Comment by tao-bioinfo** [comment]
@cement-head Thank you for your feedback!
