### ISSUE TITLE
Advice on viewing JSON data (Relative_Abundance & Diversity)

### ISSUE THREAD

**Issue by cement-head** [billzt/MiFish#7]
What graphical viewers would you recommend to view the JSON output of the CLI pipeline? TIA

**Comment by tao-bioinfo** [comment]
Although the web interface uses D3.js to show interactive graphs, for publish-quality figures, I recommend using the R library `ggplot2` to plot stacked column charts or heatmaps.

Of course, if you just want to have a quick look, Excel is also OK.
