### ISSUE TITLE
Help with multiple input data files (groups)

### ISSUE THREAD

**Issue by cement-head** [billzt/MiFish#8]
The mitofish pipeline is working when I use a single input directory, however, I am trying to analyze the data in three subgroups.  I have placed each sub-group into its own folder and specified each of the folders by using the "-d" argument. 

However, I am now getting an error (see below) with the pipeline as it seems it cannot find the database.

What am I doing wrong?

```
$ mifish -o output/WTRBA-YEARS -t 124 -d /home/cbfgws6/MiFish/WTRBA_YEAR/21 -d /home/cbfgws6/MiFish/WTRBA_YEAR/22 -d /home/cbfgws6/MiFish/WTRBA_YEAR/23 /home/cbfgws6/MiFish/mifishdb-Oct2023/mitofish.db.fa
usage: mifish [-h] [-d OTHER_DATA_DIR] [-m MIN_READ_LEN] [-M MAX_READ_LEN] [-f PRIMER_FWD] [-r PRIMER_REV] [-u UNOISE_MIN] [-i BLAST_MIN_IDENTITY] [-s] [-k]
              [-o OUTPUT_DIR] [-t THREADS]
              seq_dir db
mifish: error: the following arguments are required: db
```

**Comment by cement-head** [comment]
Whoops! I figured it out.  In the instructions the fact that the seq file is called seq confused me.

Here's the command that worked:
`
$ mifish /home/cbfgws6/MiFish/WTRBA_YEAR/21 /home/cbfgws6/MiFish/mifishdb-Oct2023/mitofish.db.fa -d /home/cbfgws6/MiFish/WTRBA_YEAR/22 -d /home/cbfgws6/MiFish/WTRBA_YEAR/23-o output/WTRBA-YEARS -t 124`

**Comment by tao-bioinfo** [comment]
I have added a note in the README file.
